// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcwuAtZU7a2CGUtpCJ0irygH-6WbbkQKE',
    appId: '1:993201967509:web:8d566a8746e2f03291269c',
    messagingSenderId: '993201967509',
    projectId: 'lawyerfinder-86944',
    authDomain: 'lawyerfinder-86944.firebaseapp.com',
    storageBucket: 'lawyerfinder-86944.appspot.com',
    measurementId: 'G-CCMKV43Q1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDef_wjVKHyoeprjNw04n6gnz8z_xk5ee0',
    appId: '1:993201967509:android:64262292d9da003191269c',
    messagingSenderId: '993201967509',
    projectId: 'lawyerfinder-86944',
    storageBucket: 'lawyerfinder-86944.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0psvuVdo07zoqCHqmupEx1zG9fQ3f130',
    appId: '1:993201967509:ios:c597d670cdd7944e91269c',
    messagingSenderId: '993201967509',
    projectId: 'lawyerfinder-86944',
    storageBucket: 'lawyerfinder-86944.appspot.com',
    iosBundleId: 'com.syedsapplication.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0psvuVdo07zoqCHqmupEx1zG9fQ3f130',
    appId: '1:993201967509:ios:32d517c7d1c3947b91269c',
    messagingSenderId: '993201967509',
    projectId: 'lawyerfinder-86944',
    storageBucket: 'lawyerfinder-86944.appspot.com',
    iosBundleId: 'com.syedsapplication.lawyerFinder.RunnerTests',
  );
}
